# borrowed from https://cloud.nholuongut.works/k8s/scope.yaml?k8s-version=1.9.3
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nholuongut-scope
  labels:
    name: nholuongut-scope
  namespace: nholuongut
roleRef:
  kind: ClusterRole
  name: nholuongut-scope
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: nholuongut-scope
    namespace: nholuongut
