# borrowed from https://cloud.nholuongut.works/k8s/scope.yaml?k8s-version=1.9.3
apiVersion: v1
kind: Service
metadata:
  name: nholuongut-scope-app
  labels:
    name: nholuongut-scope-app
    app: nholuongut-scope
    nholuongut-cloud-component: scope
    nholuongut-scope-component: app
  namespace: nholuongut
spec:
  ports:
    - name: app
      port: 80
      protocol: TCP
      targetPort: 4040
  selector:
    name: nholuongut-scope-app
    app: nholuongut-scope
    nholuongut-cloud-component: scope
    nholuongut-scope-component: app
