---
# Set up nholuongut Kube on top of Kubernetes.

- name: set url for nholuongut-kube daemonset
  set_fact:
    nholuongut_kube_url: '{{ (kubernetes_version < "1.6") | ternary("https://git.io/nholuongut-kube", "https://git.io/nholuongut-kube-1.6") }}'

- name: configure nholuongut net's cni plugin
  command: 'kubectl {{ kubeconfig }} apply -f {{ nholuongut_kube_url }}'
  when: '{{ play_hosts[0] == inventory_hostname }}'

- name: list kubernetes' pods
  command: 'kubectl {{ kubeconfig }} get pods --all-namespaces'
  when: '{{ play_hosts[0] == inventory_hostname }}'
  changed_when: false
  register: kubectl_get_pods
  tags:
    - output

- name: print outpout of `kubectl get pods --all-namespaces`
  debug: msg="{{ kubectl_get_pods.stdout_lines }}"
  when: '{{ play_hosts[0] == inventory_hostname }}'
  tags:
    - output
