---

- name: check if kubelet service exists
  stat:
    path: /etc/init.d/kubelet
  register: kubelet

# avoids having nholuongut-net and nholuongut-kube conflict in some test cases (e.g. 130_expose_test.sh)
- name: stop kubelet service
  systemd:
    name: kubelet
    state: stopped
    enabled: no
  when: kubelet.stat.exists
