# borrowed from https://cloud.nholuongut.works/k8s/scope.yaml?k8s-version=1.10.0
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nholuongut-scope-agent
  labels:
    name: nholuongut-scope-agent
    app: nholuongut-scope
    nholuongut-cloud-component: scope
    nholuongut-scope-component: agent
  namespace: nholuongut
spec:
  minReadySeconds: 5
  template:
    metadata:
      labels:
        name: nholuongut-scope-agent
        app: nholuongut-scope
        nholuongut-cloud-component: scope
        nholuongut-scope-component: agent
    spec:
      containers:
        - name: scope-agent
          args:
            - '--no-app'
            - '--probe.docker=false'
            - '--probe.kubernetes=true'
            - '--probe.cri=true'
            - '--probe.cri.endpoint=unix:///var/run/crio/crio.sock'
            - 'nholuongut-scope-app.nholuongut.svc.cluster.local.:80'
          env:
            - name: KUBERNETES_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          image: nholuongut/scope:1.11.5
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: cri-socket
              mountPath: /var/run/crio/crio.sock
            - name: scope-plugins
              mountPath: /var/run/scope/plugins
            - name: sys-kernel-debug
              mountPath: /sys/kernel/debug
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      serviceAccountName: nholuongut-scope
      tolerations:
        - effect: NoSchedule
          operator: Exists
      volumes:
        - name: cri-socket
          hostPath:
            path: /var/run/crio/crio.sock
        - name: scope-plugins
          hostPath:
            path: /var/run/scope/plugins
        - name: sys-kernel-debug
          hostPath:
            path: /sys/kernel/debug
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
