# borrowed from https://cloud.nholuongut.works/k8s/scope.yaml?k8s-version=1.10.0
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nholuongut-scope
  labels:
    name: nholuongut-scope
  namespace: nholuongut
