FROM golang:1.7
ADD ./bin/dialer /go/bin

ARG revision
LABEL maintainer="nholuongutworks <luongutnho@hotmail.com>" \
      org.opencontainers.image.title="dialer" \
      org.opencontainers.image.source="https://github.com/nholuongut/scope/tree/master/extras/dialer" \
      org.opencontainers.image.revision="${revision}" \
      org.opencontainers.image.vendor="nholuongutworks"
